spring:
  application:
    name: macrocore-backend
  web:
    cors:
      allowed-origins: "https://macrocore.pages.dev/"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

server:
  port: 8080

management.endpoints.web.exposure.include: health,info