spring:
  web:
    cors:
      allowed-origins: "http://localhost:5173,http://127.0.0.1:5173"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

server:
  port: 8080

logging:
  level:
    org.grimjo.macrocore: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE